CONFIG_VLOS_ROLE_INITIATOR=n
CONFIG_VLOS_NODE_ID="node_B"
CONFIG_VLOS_UWB_PROFILE_ROBUST=y
CONFIG_VLOS_IDENTITY_INTERVAL_MS=5000
CONFIG_VLOS_HEARTBEAT_INTERVAL_MS=1000
CONFIG_VLOS_WATCHDOG_SOFT_MS=2000
CONFIG_VLOS_WATCHDOG_REINIT_MS=10000
CONFIG_VLOS_TX_RESP_LATE_MS=8